name: cpfcnpj
description: An easy-to-use utility for CPF/CNPJ validation and formatting.
version: 2.0.0
homepage: https://github.com/thiagopereiramartinez/dart-cpfcnpj
author: Thiago P. Martinez <thiago.pereira.ti@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
